version: '3.8'
services:
  jekyll:
    image: jekyll-site
    ports:
      - "4000:4000"
    volumes:
      - /home/pc/dev/kyle-paul.github.io:/usr/src/app
    command: jekyll serve --watch --force_polling --host 0.0.0.0